#!/usr/bin/env bash 

git config --global push.default simple
git config --global credential.helper cache
git config --global alias.s "status"
git config --global alias.print "log --branches --pretty=format:'%C(yellow)%h|%Cred%ad|%Cblue%an|%Cgreen%d %Creset%s' --date=local"
git config --global alias.p "log --pretty=format:'%C(yellow)%h|%Cred%ad|%Cblue%an|%Cgreen%d %Creset%s' --date=local"
git config --global alias.sprint "log --branches --pretty=format:'%C(yellow)%h|%Cred%ad|%Cblue%an|%Cgreen%d %Creset%s' --date=local -n 20"
git config --global alias.sp "log --branches --pretty=format:'%C(yellow)%h|%Cred%ad|%Cblue%an|%Cgreen%d %Creset%s' --date=local -n 20"
git config --global alias.ps "log --branches --pretty=format:'%C(yellow)%h|%Cred%ad|%Cblue%an|%Cgreen%d %Creset%s' --date=local -n 20"
git config --global alias.changed-files "diff-tree --no-commit-id --name-only -r"
git config --global alias.chfiles "diff-tree --no-commit-id --name-only -r"
git config --global color.branch auto
git config --global color.ui auto
git config --global color.status.branch cyan
