#!/usr/bin/env bash 

# execute lines individually by  :.w !bash   (use space between w and !)

# ======= GENERAL ========

# download neovim to software folder
mkdir -p ~/software
curl -Lo ~/software/nvim.appimage https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
ln -s ~/software/nvim.appimage ~/bin/vim
# ln -s ~/software/nvim.appimage ~/bin/nvim

# download ranger
mkdir -p ~/software/ranger-1.9.1/
curl -Lo ~/software/ranger.tar.gz "https://github.com/ranger/ranger/archive/v1.9.1.tar.gz"
tar zxvf ~/software/ranger.tar.gz -C ~/software/ranger-1.9.1/
rm ~/software/ranger.tar.gz 
ln -s ~/software/ranger-1.9.1/ranger.py ~/bin/ranger


# ======= SET LINKS ======

# vim
mkdir -p ~/.vim
mv ~/.vim/vimrc ~/.vim/vimrc_bak; ln -s $(pwd)/.vim/vimrc ~/.vim/vimrc

# nvim
mkdir -p ~/.config/nvim
mv ~/.config/nvim/init.vim ~/.config/nvim/init.vim_bak; ln -s $(pwd)/.vim/vimrc ~/.config/nvim/init.vim

# zsh
# mv ~/.zshrc.local ~/.zshrc.local_bak; ln -s $(pwd)/.zshrc.local ~/.zshrc.local

# bash
mv ~/.bash_oma ~/.bash_oma_bak; ln -s $(pwd)/.bash_oma ~/.bash_oma

# feh
# mv ~/.config/feh/keys ~/.config/feh/keys_bak; mkdir -p ~/.config/feh; ln -s $(pwd)/.config/feh/keys ~/.config/feh/keys

# ideavimrc
mv ~/.ideavimrc ~/.ideavimrc_bak; ln -s $(pwd)/.ideavimrc ~/.ideavimrc


# ranger
mkdir -p ~/.trash
mkdir -p ~/.config/ranger
touch ~/.config/rangerdir
mv ~/.config/ranger/commands.py ~/.config/ranger/commands.py_bak; ln -s $(pwd)/.config/ranger/commands.py ~/.config/ranger/commands.py
mv ~/.config/ranger/rc.conf ~/.config/ranger/rc.conf_bak; ln -s $(pwd)/.config/ranger/rc.conf ~/.config/ranger/rc.conf
mv ~/.config/ranger/rifle.conf ~/.config/ranger/rifle.conf_bak; ln -s $(pwd)/.config/ranger/rifle.conf ~/.config/ranger/rifle.conf

# i3
mkdir -p ~/.i3/scripts
mv ~/.i3status.conf ~/.i3status.conf_bak; ln -s $(pwd)/.i3status.conf ~/.i3status.conf
mv ~/.i3/config ~/.i3/config_bak; ln -s $(pwd)/.i3/config ~/.i3/config
mv ~/.i3/scripts/ws_switcher  ~/.i3/scripts/ws_switcher_bak; ln -s $(pwd)/.i3/scripts/ws_switcher ~/.i3/scripts/ws_switcher 
mv ~/.config/compton.conf ~/.config/compton.conf_bak; ln -s $(pwd)/.config/compton.conf ~/.config/compton.conf

